### ISSUE TITLE
Support for new jinja2 version of gettext 

### ISSUE THREAD

**Issue by AnderUstarroz** [Pylons/pyramid_jinja2#108]
Hi, I've realized that the **i18n.py** functions are out of date. The gettext functions in the [jinja2 documentation](http://jinja.pocoo.org/docs/dev/extensions/#newstyle-gettext) allow variable mapping with different/shorter syntax.

**Comment by domenkozar** [comment]
Yeah I saw that too - didn't have time to implement it during #pycon sprints

**Comment by petterroea** [comment]
Hello! I found this issue while trying to understand how to enable this myself.

I believe this is now resolved. You can enable it by passing `jinja2.newstyle = true` in your pyramid config :D

**Comment by mmerickel** [comment]
Agreed I think you're right. Thank you for the note.
