### ISSUE TITLE
Loading jinja2 templates dynamically from a Pyramid view

### ISSUE THREAD

**Issue by AnderUstarroz** [Pylons/pyramid_jinja2#109]
Following  the [jinja2 documentation](http://jinja.pocoo.org/docs/dev/api/) I've find out a way to load different templates from a unique view. But taking into account that Pyramid_jinja2 was already configured in my app with a default path for templates.  I was wondering if there is another way more elegant to get this done. This is my approach:

	from jinja2 import Environment, PackageLoader

	@view_config(context=Test)
	def test_view(request):
	    env = Environment(loader=PackageLoader('project_name', 'templates'))
	    template = env.get_template('section1/example1.jinja2')
	    return Response(template.render(data={'a':1,'b':2}))

Can I get an instance of the **pyramid_jinja2** environment from somewhere so I don't have to set again the default path for templates in the view?

**Comment by stevepiercy** [comment]
Cross-post http://stackoverflow.com/questions/30185574/load-jinja2-templates-dynamically-on-a-pyramid-view

@AnderUstarroz It sounds like you are requesting support. Please see http://www.pylonsproject.org/community/get-support, and if this in fact a request for support, then close this issue and use more appropriate channels.

**Comment by mmerickel** [comment]
The correct answer is to use `p.renderers.render_to_response` or `p.renderers.render('project_name:templates/section1/example1.jinja2', {}, request=request)` from within your view. You can then render whatever you want that way using an asset spec.
