### ISSUE TITLE
Bug in GETTEXT  when loading templates dynamically

### ISSUE THREAD

**Issue by AnderUstarroz** [Pylons/pyramid_jinja2#110]
I'm using **jinja2** templates dynamically in pyramid. It works fine for basic usage, but it fails when trying to load internationalized text with the GETTEXT() function:

```
@view_config(context=Test)
def test_view(request):
    #Render templates dynamically:
    template = "template1.jinja2"
    return Response(render(template, {'test1':1}, request=request))
```

Basic jinja2 template:

```
<!-- template/template1.jinja2 -->
{{ GETTEXT('NAME') }} - {{ test1 }}
```

Throws the following error:

```
File "/python3.4/site-packages/pyramid/i18n.py", line 218, in get_localizer
    return request.localizer
AttributeError: 'NoneType' object has no attribute 'localizer'
```

I've tracked the error,  it seems to be a problem on file **pyramid_jinja2/i18n.py** when the function **localizer()** is calling **i18n.get_localizer(get_current_request())**, but the  function **get_current_request()** generates a **None** value. So it's not being able to create a valid Request.

```
class GetTextWrapper(object):

   ....

    @property
    def localizer(self):
        return i18n.get_localizer(get_current_request())

   ....
```

**Comment by mmerickel** [comment]
When are you invoking this test? The only scenario I usually see where someone is having issues with `get_current_request` is in tests themselves where they haven't called `config.begin()`. During a normal request cycle it should definitely not be `None`.

**Comment by mmerickel** [comment]
No followup from the OP. I'm closing the issue as I do not think there's actually a bug here.
