### ISSUE TITLE
Templates not found in sub-directories (add_jinja2_search_path )

### ISSUE THREAD

**Issue by martinstein** [Pylons/pyramid_jinja2#113]
When you add a directory to the jinja-search path normally, like this:

``` python
config.add_jinja2_search_path('pyramid_jinja_issue:templates', name='.html')
```

then Pyramid/Jinja won't find the template when it's located in a sub-directory. This one works:

``` python
@view_config(route_name='works', renderer='some_template.html')
def my_view(request):
    ...
```

but this one doesn't work:

``` python
@view_config(route_name='broken', renderer='email/other_template.html')
def my_view(request):
    ...
```

Providing the full asset-specification works again, but the other way based on the search-path should work, too.

Example to reproduce here (simply try the 3 different routes `/works`, `/works2`, `/broken`:
https://github.com/martinstein/pyramid_jinja_issue

**Comment by diefans** [comment]
I made a fresh clone and virtualenv installation and was not able to reproduce your issue:

```
git clone https://github.com/martinstein/pyramid_jinja_issue
cd pyramid_jinja_issue
mkvirtualenv pyramid_jinja_issue
pip install -e .
pserve development.ini
```
```
curl http://localhost:6543/works -I
HTTP/1.1 200 OK
Content-Length: 753
Content-Type: text/html; charset=UTF-8
Date: Thu, 09 Jul 2015 10:14:02 GMT
Server: waitress
```
```
curl http://localhost:6543/works2 -I
HTTP/1.1 200 OK
Content-Length: 753
Content-Type: text/html; charset=UTF-8
Date: Thu, 09 Jul 2015 10:14:09 GMT
Server: waitress
```
```
curl http://localhost:6543/broken -I
HTTP/1.1 200 OK
Content-Length: 753
Content-Type: text/html; charset=UTF-8
Date: Thu, 09 Jul 2015 10:14:14 GMT
Server: waitress
```

**Comment by martinstein** [comment]
Just to make sure, I created another virtualenv, too, and I can still reproduce the issue. I get the error:
```
`OSError: [Errno 22] Invalid argument: 'PATH_TO_REPOSITORY\\pyramid_jinja_issue\\pyramid_jinja_issue\\templates\\pyramid_jinja_issue:email\\other_template.html
```
I'm running Python 3.4.3 on Windows 7. Which environment/Python are you on?

**Comment by diefans** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

I just tried it with python2.7 and python3.4 in ubuntu trusty and both are working as expected

Your error looks like the part before the colon ":" is handled as Drive-Letter (I have not so deep Windows knowledge)
resp. the package name is not properly recognized...

I have no further idea for you, since I am not able to reproduce, but I suggest that you put a debugger somewhere
before the exception and inspect your case: expected vs. manifested



On 09.07.2015 13:50, Martin Stein wrote:
> Just to make sure, I created another virtualenv, too, and I can still reproduce the issue. I get the error:
> 
> |`OSError: [Errno 22] Invalid argument: 
> 'PATH_TO_REPOSITORY\\pyramid_jinja_issue\\pyramid_jinja_issue\\templates\\pyramid_jinja_issue:email\\other_template.ht
ml
>
>
> 
|
> 
> I'm running Python 3.4.3 on Windows 7. Which environment/Python are you on?
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/Pylons/pyramid_jinja2/issues/113#issuecomment-119925011>.
> 
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iEYEARECAAYFAlWeZGwACgkQ0SdHlaw3iad1tgCfbSrniijUOxCQtShtR3Ou2PAC
v5kAoJGgJ3gSYkscPOU4quNAjRTvG4NV
=A7iR
-----END PGP SIGNATURE-----

**Comment by mmerickel** [comment]
Thank you for your example. I can confirm it works on my 10.10 OSX machine as well. I will try to find some time to spin up a windows VM and give this a try as I suspect that is the issue.

**Comment by mmerickel** [comment]
This looks similar to #107.

**Comment by domenkozar** [comment]
Thank you for a simple http://sscce.org/!

I've reproduced the issue on Windows 7. Upgrading to latest pyramid_jinja2 shows the error has already been fixed (and I've found a test that covers exactly this case).
