### ISSUE TITLE
[Resolved]Log warnings while sphinx generate documentation

### ISSUE THREAD

**Issue by alexsun** [Pylons/pyramid_jinja2#114]
versions: Python 3.5.0, Pyramid: v1.6 

http://docs.pylonsproject.org/projects/pyramid-jinja2/en/latest/ -> 404

(env) docs > make html 
cd ..; git submodule update --init --recursive; cd docs;
mkdir -p _build/html _build/doctrees
sphinx-build -b html -d _build/doctrees  -W . _build/html
Running Sphinx v1.3.1
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.pylonsproject.org/projects/translationstring/en/latest/objects.inv...
loading intersphinx inventory from http://docs.sqlalchemy.org/en/latest/objects.inv...
loading intersphinx inventory from http://docs.python.org/objects.inv...
loading intersphinx inventory from http://docs.pylonsproject.org/projects/pyramid-jinja2/en/latest/objects.inv...

Warning, treated as error:
WARNING: intersphinx inventory 'http://docs.pylonsproject.org/projects/pyramid-jinja2/en/latest/objects.inv' not fetchable due to <class 'urllib.error.HTTPError'>: HTTP Error 404: OK

make: *** [html] Error 1

also in few other projects have 404, for example:
http://docs.pylonsproject.org/projects/pyramid-zcml/en/latest/

Thanks for an advice

**Comment by alexsun** [comment]
../env/bin/sphinx-build -b html -d _build/doctrees  . _build/html 
without -W option

**Comment by stevepiercy** [comment]
Previously reported to RTD as https://github.com/rtfd/readthedocs.org/issues/1776

**Comment by stevepiercy** [comment]
@alexsun this was an issue with RTD, [which was resolved earlier today](https://github.com/rtfd/readthedocs.org/issues/1776#issuecomment-149723792). I would recommend that you revert your Sphinx configuration to the original so you do not ignore warnings because they are informative.
