### ISSUE TITLE
release 2.6

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_jinja2#117]
Howdy, @mmerickel @domenkozar @rockyburt or @mcdonc 

I've updated the scaffold to be consistent with Pyramid's default scaffolds in PR #116, and updated changes.txt. I'd like to push a release to PyPI. Is there anything I can do to help?

**Comment by stevepiercy** [comment]
Also resolve #119 before release.

**Comment by stevepiercy** [comment]
Pyramid docs are now updated with the PRs #116 and #118 in https://github.com/Pylons/pyramid/pull/2246

**Comment by domenkozar** [comment]
I've released 2.6, no time right now to update tests :) Thanks for leading this effort @stevepiercy
