### ISSUE TITLE
switch to py.test and pip

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_jinja2#123]
With the release of Pyramid 1.7, we've switched from nose and coverage to py.test and pytest-cov, and have added default configuration for both. We've also switched from easy_install to pip.

See:
* http://docs.pylonsproject.org/projects/pyramid/en/1.7-branch/whatsnew-1.7.html#documentation-enhancements
* https://github.com/Pylons/pyramid/pull/2550

**Comment by domenkozar** [comment]
Pip has been used since https://github.com/Pylons/pyramid_jinja2/commit/277d92258fde1dfda9509ff86d5d4843c2397618, now just pytest part is missing.

**Comment by stevepiercy** [comment]
I've made a new branch for this work. https://github.com/Pylons/pyramid_jinja2/tree/feature-123-pytest

To clarify the scope of this issue, I am working on only documentation and the scaffold. I am not certain whether you want to switch to pytest from nose on the pyramid_jinja2 core package itself, as there was some [discussion about this for Pyramid](https://github.com/Pylons/pyramid/issues/2474#issuecomment-209654173).

**Comment by stevepiercy** [comment]
@domenkozar I'd appreciate another pair of eyes on the PR #132. I've tested it out by running through the documentation to create a new project from the scaffold, install test dependencies, and run tests, and it works for me, but it would be good to get your feedback.
