### ISSUE TITLE
Typo in the default template in trans tag causes i18n to fail

### ISSUE THREAD

**Issue by navinkarkera** [Pylons/pyramid_jinja2#125]
The missing "!" in the template causes mismatch between trans tag string and the msgid in the pot file.

**Comment by stevepiercy** [comment]
@navinkarkera which file specifically?

**Comment by navinkarkera** [comment]
Project created using scaffold pyramid_jinja2_starter, templates folder, mytemplate.jinja2

https://github.com/Pylons/pyramid_jinja2/blob/master/pyramid_jinja2/scaffolds/jinja2_starter/%2Bpackage%2B/templates/mytemplate.jinja2_tmpl

Line number 41

**Comment by stevepiercy** [comment]
@navinkarkera I'm not familiar with the syntax. Sorry.

I reckon if you submit a PR with your proposed fix, then this issue has a better chance of getting resolved by the project maintainers.

**Comment by navinkarkera** [comment]
The po files for de and fr languages are marked as fuzzy so the missing "!" mark causes problem

**Comment by stevepiercy** [comment]
@navinkarkera please submit a pull request for the maintainers to review. Thank you!

**Comment by domenkozar** [comment]
@navinkarkera could you provide a http://sscce.org/ ?

**Comment by navinkarkera** [comment]
I'll submit a pull request with a fix.

**Comment by stevepiercy** [comment]
This was actually not due to the "!", but due to the scaffolds containing the fuzzy markers. Rather than remove the fuzzy markers, I thought it best to leave them there and write documentation as a learning opportunity for the reader.

Fixed in #138
