### ISSUE TITLE
ModuleNotFoundError: No module named 'pyramid_Jinja2'

### ISSUE THREAD

**Issue by MahamdiAmine** [Pylons/pyramid_jinja2#149]
from wsgiref.simple_server import make_server
from pyramid.config import Configurator
from pyramid.view import view_config

@view_config(route_name='hello_world', renderer='hello.jinja2')
def hello(request):
    return dict(name='World')

if __name__ == '__main__':
    config = Configurator()
    config.include('pyramid_jinja2')
    config.add_route('hello_world', '/')
    config.scan()
    app = config.make_wsgi_app()
    server = make_server('0.0.0.0', 6543, app)
    print ('Serving at http://127.0.0.1:6543')
    server.serve_forever()

**Comment by mcdonc** [comment]
You must install pyramid_jinja2 via e.g.

``pip install pyramid_jinja2``
