### ISSUE TITLE
Fix pypy version on Travis

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_jinja2#154]
A recent build failed due to a bad version of pypy.

https://travis-ci.org/Pylons/pyramid_jinja2/jobs/635522957#L164

`Unable to download pypy-5.4.1 archive. The archive may not exist. Please consider a different version.`

I can't remember which other Pylons repo had the same issue and how we fixed it.

**Comment by bertjwregeer** [comment]
This is an issue on pyramid_debugtoolbar too. I have a feeling many of our jobs are going to fail because of it.

**Comment by stevepiercy** [comment]
Here is the list of available pypy binaries:
https://docs.travis-ci.com/user/languages/python/#python-versions

And this community thread indicates that `pypy` or `pypy3` alone are insufficient, and that an explicit version must be used.
https://travis-ci.community/t/confusing-pypy-versions/2505

**Comment by stevepiercy** [comment]
I reckon that at this point we don't care about `pypy`, but we might care about `pypy3`. Is that correct? If so I'll take another stab at getting `pypy3.6-7.1.1` to work.

**Comment by stevepiercy** [comment]
In Pyramid, [plain old `pypy3` works](https://github.com/Pylons/pyramid/blob/master/.travis.yml#L11), so I assume it would work here as well.

At one point we had PyPy3 support, then dropped it, so I reckon we should restore pypy3 support since we can run tests against it. That leaves whether to keep support for pypy.

**Comment by bertjwregeer** [comment]
This was fixed in: https://github.com/Pylons/pyramid_jinja2/pull/158
