### ISSUE TITLE
Requires Jinja2 3.0, but doesn't declare so

### ISSUE THREAD

**Issue by MarcSchmitzer** [Pylons/pyramid_jinja2#163]
pyramid_jinja2 requires Jinja2 3.0 since use of [`pass_context`](https://jinja.palletsprojects.com/en/3.0.x/api/?highlight=pass_context#jinja2.pass_context) was added in commit 8093938422ac0f8af6fc8fe028f9613e2e41117c , but `setup.cfg` still gives the minimum Jinja2 version as 2.5.0: https://github.com/Pylons/pyramid_jinja2/blob/ea3e27839f7cd600dc545fe9852f6c9b515fbd81/setup.cfg#L38 
This is rather problematic because Jinja2 3.0 introduces breaking changes that projects may not be ready to deal with.
Note that fixing this would probably require yanking 2.9 and 2.9.1 to ensure that no version containing the `pass_context` use is installable with Jinja2 2.x.

**Comment by mmerickel** [comment]
I was not aware that the PR had introduced a dependency on 3.0. I need to verify but that would indeed be bad and I would’ve not released it as a minor version update. I will pull those releases after verifying.

**Comment by mmerickel** [comment]
Thank you @MarcSchmitzer! I confirmed that things are broken and have yanked the release from pypi and updated the changelog.

I'll need to re-evaluate if there's a way to release this with support for both versions, or if I should issue a major release that drops 2.x.

**Comment by MarcSchmitzer** [comment]
Great, thanks :+1:
