### ISSUE TITLE
Scaffold should include dependency on nose and install pyramid_debugtoolbar

### ISSUE THREAD

**Issue by pauleveritt** [Pylons/pyramid_jinja2#61]
Another note about me doing Getting Started docs. I'm advocating that complete newbies start with debugtoolbar. If I'm preaching pyramid_jinja2 and its starter template, it would be better if that starter template made pyramid_debugtoolbar a dependency and put it in development.ini pyramid includes.

Similarly, some other nice-to-haves in the scaffold:

- Use waitress

- Install nose as the test runner

**Comment by marioidival** [comment]
I hope it helped :)
