### ISSUE TITLE
Locale in request is ignored

### ISSUE THREAD

**Issue by rbu** [Pylons/pyramid_jinja2#97]
The GetText callables installed by pyramid_jinja2 do not honor the request given to the render function but always use the global request instead.

While the existence of a global request is an acceptable default, the Jinja2 renderer should prefer an explicit request whenever it is provided. Calling it like so:

``` py
from pyramid.renderers import render

request = DummyRequest(...)
assert request.locale_name == 'es'

render('some.jinja2', dict(), request=request)
```

Then the locale from `get_current_request()` will be used instead of the one explicitly specified.

**Comment by iElectric** [comment]
Hmm, the same bug exists in `pyramid_chameleon`. Someone will have to check if it's possible to even pass the `request` to the code that creates `localizer`

**Comment by marioidival** [comment]
Well, I did a quick search and found this code snippet in Django, which recently added Jinja2 in its dependencies.  Maybe you can help.

https://github.com/django/django/blob/master/django/template/backends/jinja2.py#L51

**Comment by domenkozar** [comment]
Now you can override `pyramiid_jinja.i18n.GetTextWrapper`, but it'd still be interested to fix this.

**Comment by mmerickel** [comment]
Just looked at this again and I don't see a way to access the rendering context inside the gettext extension. I'm going to close this but if jinja2 adds a new feature to the extensions allowing access to the context then we can revisit.
